### ISSUE TITLE
申请添加资源笔记功能

### ISSUE THREAD

**Issue by 447V** [BAKAOLC/Ritsukage-Core#25]
可以存放一些资源下载链接给bot，后续有人询问的时候可以直接使用bot拉出消息
如 查看现有资源
活7
活6
东方幕华祭红月篇1.0版本
东方真珠岛
（以及其他）
这种，然后 获取资源 活7
下载链接: https://pan.baidu.com/s/1i5ra8G9 密码: 4wxm
这种，大概，不知道会不会有用）x

**Comment by BAKAOLC** [comment]
这个功能有个问题在于资源链接的来源不好掌握，同时管理方面存在难度，可能出现乱七八糟的提交，或者失效资源难以替换等
暂时先列进TODO，待定

**Comment by BAKAOLC** [comment]
因为优先度极低且没有管理能力因此暂时否决
