### ISSUE TITLE
Allow tip message uses the output of command or Schedule tasks support

### ISSUE THREAD

**Issue by KunoSayo** [BAKAOLC/Ritsukage-Core#55]
+tipcommand <时间> [间隔] [结束时间]  <command>    -- 在时间之后每[间隔]时间直到[结束时间]，输出以执行人权限执行command的结果。

可能的例子：
```plaintext
+tipcommand 2024-01-01T06:00 1D 2024-06-11T00:00 +高考倒计时
```

或应该等同于计划任务
+schedule <时间> [间隔] [结束时间] <command/lua_script_name/system command...> -- （superuser only的命令）

<hr>
顺便问问现在如果开发新命令是pr到master还是等v2写好后整pr (x)(pr的命令想法与该issue无关）

**Comment by BAKAOLC** [comment]
master即可，v2预计会用语义感知，任务上下文记录等部件构成，工作方式不一致，会重新设计构建一套新的指令集

**Comment by BAKAOLC** [comment]
原有框架逻辑不适合构建制作该方法
